spring:
  application:
    name: gateWay
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: gateWay
      profile: prod
    gateway:
      routes:
        - id: dummyApi
          uri: lb://DUMMYAPI
          predicates:
            - Path=/dummyApi/**
          filters:
            - RewritePath=/dummyApi/(?<segment>.*), /$\{segment}

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka