spring:
  application:
    name: dummyApi
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: dummyApi
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans ,env

service:
  name: local test